name: HydroBench
channels:
  - conda-forge
  - defaults
dependencies:
  - pygeoogc=0.11.0
  - pygeoutils=0.11.0
  - py3dep=0.11.0
  - pynhd=0.11.0
  - pygeohydro=0.11.0
  - pydaymet=0.11.0
  - openpyxl
  - cdsapi
  - cfgrib
  - tqdm
  - sphinx
  - pytest